Documentation:
  Enabled: false

AllCops:
  Include:
    - rubocop-rspec
  Exclude:
    - 'Gemfile*'
    - 'Rakefile'
    - 'bin/*'
    - 'spec/spec_helper\.rb'
  TargetRubyVersion: 2.2

# skips style of child classes and modules.
Style/ClassAndModuleChildren:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - '*.gemspec'
    - 'spec/*/**'
  ExcludedMethods: ['describe', 'context', 'shared_examples']

Metrics/LineLength:
  Max: 100
