#!/usr/bin/env ruby
require 'bundler/setup'
require 'gifs'

if ENV[Gifs::ENV_DIR_KEY]
  ENV[Gifs::ENV_DIR_KEY] = File.expand_path ENV[Gifs::ENV_DIR_KEY]
else
  ENV[Gifs::ENV_DIR_KEY] = File.expand_path '~/Dropbox/gifs'
end

puts Gifs::Directory.new(criteria: ARGV).to_s
